spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
  application:
    name: cloud-gateway


server:
  port: 8085

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8081/eureka/